// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtiZFMYjEBvHm7O90ocDfk3OWcor2fRo',
    appId: '1:434822482657:web:8583d7f64ba56032f6c5a0',
    messagingSenderId: '434822482657',
    projectId: 'rentapp02',
    authDomain: 'rentapp02.firebaseapp.com',
    storageBucket: 'rentapp02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRA5J5caKMWAhQBD98PqMT6ygfnvd7mos',
    appId: '1:434822482657:android:62a994e26de5b0a1f6c5a0',
    messagingSenderId: '434822482657',
    projectId: 'rentapp02',
    storageBucket: 'rentapp02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3z0ylEqh1JPdRUrI92tLvS0jJZNW137Y',
    appId: '1:434822482657:ios:d466ca60bfc0dbaff6c5a0',
    messagingSenderId: '434822482657',
    projectId: 'rentapp02',
    storageBucket: 'rentapp02.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3z0ylEqh1JPdRUrI92tLvS0jJZNW137Y',
    appId: '1:434822482657:ios:d466ca60bfc0dbaff6c5a0',
    messagingSenderId: '434822482657',
    projectId: 'rentapp02',
    storageBucket: 'rentapp02.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbtiZFMYjEBvHm7O90ocDfk3OWcor2fRo',
    appId: '1:434822482657:web:075c2431c6adf926f6c5a0',
    messagingSenderId: '434822482657',
    projectId: 'rentapp02',
    authDomain: 'rentapp02.firebaseapp.com',
    storageBucket: 'rentapp02.firebasestorage.app',
  );

}